tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Finding, browsing & reading files
brew "bat"
brew "broot"
brew "fd"
brew "fzf"
brew "ranger"

# Git & Github
brew "gh"
brew "grip"
brew "lazygit"

# DB stuff
brew "pgcli"

# Node packages (nvm + node installed separately in os/dev_packages.sh)
brew "yarn"

# Scripts
brew "shellcheck"

# Super important stuff
brew "cmatrix"
