#!/bin/bash

[ -n "$PS1" ] \
    && . "$HOME/.bash_profile"

# random colorscript when opening terminal

colorscript random

# source /home/henri.kestio/.config/broot/launcher/bash/br

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
